# prometheus.yml
# Define scraping básico para el propio servidor Prometheus en el stack local.
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
